version: '2'
services:
  elasticsearch:
    hostname: elastic
    domainname: elk-local
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_HEAP_SIZE=1G
      - ES_JAVA_OPT="-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - data:/data
  kibana:
    hostname: kibana
    domainname: elk-local
    image: kibana
    ports:
      - "80:5601"
  logstash:
    hostname: logstash
    domainname: elk-local
    command: logstash -e 'input { stdin {  } http { port => 8080 } } output { elasticsearch { hosts => [ 'elasticsearch' ] index => "elk-data-%{+YYYY.MM.dd}" } stdout { } }'
    image: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "8080:8080"
volumes:
  data:
    driver: local
